from pathlib import Path
import re

files = [
    'index.html', 'about.html', 'journey.html', 'voluntary.html',
    'awards.html', 'art.html', 'captures.html', 'projects.html'
]

shared_css = '''@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Thin_0756e8e8.ttf) format("truetype");font-weight:100;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-ExtraLight_8391e7ec.ttf) format("truetype");font-weight:200;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Light_60c18d7d.ttf) format("truetype");font-weight:300;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Regular_a0bf60ef.ttf) format("truetype");font-weight:400;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Medium_31c92d01.ttf) format("truetype");font-weight:500;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-SemiBold_1b3bfa1e.ttf) format("truetype");font-weight:600;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Bold_5590990c.ttf) format("truetype");font-weight:700;font-style:normal}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Regular_9d0a1f7a.ttf) format("truetype");font-weight:400;font-style:italic}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Medium_4477fda6.ttf) format("truetype");font-weight:500;font-style:italic}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-SemiBold_3b300050.ttf) format("truetype");font-weight:600;font-style:italic}
@font-face{font-family:JetBrains Mono;src:url(../fonts/JetBrainsMono-Bold_4039d5ce.ttf) format("truetype");font-weight:700;font-style:italic}
:root{--color-primary:#0a84ff;--color-primary-dark:#006cb0;--color-secondary:#0a84ff;--color-white:#FFFFFF;--color-black:#000000;--color-text-primary:#000000;--color-text-secondary:#333;--color-text-tertiary:#555;--color-text-light:#666;--color-text-lighter:#777;--color-text-muted:#6c757d;--color-text-very-light:#aaaaaa;--color-text-subtle:#cccccc;--color-bg-primary:#FFFFFF;--color-bg-secondary:#f8f9fa;--color-bg-tertiary:#f6f8fa;--color-bg-quaternary:#f4f4f4;--color-bg-light:#f0f2f5;--color-bg-dark:#1a1a1a;--color-bg-darker:#2a2a2a;--color-bg-black:#000000;--color-border-primary:#e1e5e9;--color-border-light:#eee;--color-border-dark:#333;--color-link:#0a84ff;--color-danger:#d73a49;--shadow-light:rgba(0,0,0,.08);--shadow-medium:rgba(0,0,0,.1);--shadow-strong:rgba(0,0,0,.12);--shadow-overlay:rgba(0,0,0,.3);--shadow-modal:rgba(0,0,0,.7);--shadow-backdrop:rgba(0,0,0,.9);--shadow-white:rgba(255,255,255,.1);--color-accent:var(--color-primary);--color-hover:var(--color-primary);--color-focus:var(--color-secondary);--color-lightbox-bg:#1a1a1a;--color-lightbox-bg-image:#000000;--color-lightbox-bg-item:#2a2a2a;--color-lightbox-border:#333;--color-lightbox-outer-border:#444;--color-lightbox-text-primary:#ffffff;--color-lightbox-text-secondary:#cccccc;--color-lightbox-text-tertiary:#aaaaaa}
[data-theme=dark]{--color-text-primary:#ffffff;--color-text-secondary:#cccccc;--color-text-tertiary:#aaaaaa;--color-text-light:#999;--color-text-lighter:#888;--color-text-muted:#a1aab4;--color-text-very-light:#777;--color-text-subtle:#555;--color-bg-primary:#18181b;--color-bg-secondary:#27272a;--color-bg-tertiary:#3a3a3c;--color-bg-quaternary:#4a4a4e;--color-bg-light:#58585c;--color-bg-dark:#f0f2f5;--color-bg-darker:#f6f8fa;--color-bg-black:#ffffff;--color-border-primary:#333;--color-border-light:#444;--color-border-dark:#e1e5e9;--color-link:#8ab4f8;--color-danger:#f88a95;--shadow-light:rgba(255,255,255,.08);--shadow-medium:rgba(255,255,255,.1);--shadow-strong:rgba(255,255,255,.12);--shadow-overlay:rgba(0,0,0,.5);--shadow-modal:rgba(0,0,0,.8);--shadow-backdrop:rgba(0,0,0,.95);--shadow-white:rgba(0,0,0,.1)}
html,body,button,input,select,textarea{font-family:JetBrains Mono,Courier New,Monaco,Menlo,monospace!important}
h1,h2,h3,h4,h5,h6,p,a,span,li,div,strong,small,code,pre,nav{font-family:inherit!important}
body{margin:0;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;background-color:var(--color-bg-primary);color:var(--color-text-primary);font-weight:600}
*{margin:0;padding:0;box-sizing:border-box;line-height:1.8}
body,html{height:100%;width:100%;scroll-behavior:smooth}
#root{min-height:100vh;display:flex;flex-direction:column}.site-container{max-width:1000px;margin:0 auto;padding:20px;min-height:100vh;display:flex;flex-direction:column;width:100%}.main-content{flex:1}.about-section{padding:100px 0;max-width:100%;margin:0 auto}.about-section>p{font-size:1.2em;margin-top:10px}.about-section>ul{list-style:disc;padding-left:40px;font-size:1.2em}.about-section ul li{margin-bottom:0}
h1{font-size:2.8em;font-weight:600}strong{font-weight:800}
::selection{background-color:var(--color-primary);color:var(--color-white)}::-moz-selection{background-color:var(--color-primary);color:var(--color-white)}
a:not(.social-link){font-weight:700;text-decoration:underline;text-decoration-color:var(--color-primary);text-decoration-thickness:3px;text-underline-offset:6px;color:var(--color-text-primary);transition:all .3s ease;background-image:none;background-size:auto;background-repeat:repeat;background-position:0 0}a:not(.social-link):hover{background-color:var(--color-hover);color:var(--color-white)}
.title-hashtag{color:var(--color-primary);font-size:.9em;margin-right:.1em}.project-title-link:hover{color:var(--color-link)}
.app-header{display:flex;justify-content:space-between;align-items:center;padding:40px 0 20px;gap:20px;flex-wrap:wrap}.header-left,.header-right{display:flex;align-items:center;gap:14px}.name-link{font-size:2.2em;font-weight:700;color:var(--color-text-primary)!important;text-decoration-color:var(--color-primary)!important}.social-icons{display:flex;gap:10px}.social-link{color:var(--color-text-primary);font-size:1.4em;text-decoration:none}.nav-links{display:flex;gap:20px;flex-wrap:wrap}.nav-links a{color:var(--color-text-primary)!important;text-decoration-color:var(--color-primary)!important}.nav-links a.active{color:var(--color-text-primary)!important}
.footer{padding:20px 0;margin-top:auto;width:100%}.footer-content{max-width:1200px;margin:0 auto;padding:0 20px;text-align:center}.copyright{margin:0;color:var(--color-text-muted);font-size:14px;line-height:1.5}.theme-toggle-button{background:0 0;border:none;cursor:pointer;padding:0;display:flex;align-items:center;justify-content:center;color:var(--color-text-primary);position:fixed;top:20px;left:20px;z-index:1000;width:40px;height:40px;border-radius:50%;background-color:var(--color-bg-secondary);box-shadow:0 2px 4px var(--shadow-light)}.theme-toggle-button svg{width:20px;height:20px}
.projects-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:30px;width:100%;max-width:960px;margin:30px 0 0}.project-card{background:var(--color-bg-primary);border:1px solid var(--color-border-primary);border-radius:12px;box-shadow:0 2px 6px var(--shadow-light);padding:20px 20px 14px;transition:border-color .25s ease,box-shadow .25s ease,transform .25s ease;min-height:100%}.project-card:hover{border-color:var(--color-secondary);box-shadow:0 8px 22px var(--shadow-light);transform:translateY(-2px)}.project-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:8px}.project-link-icon{display:inline-flex;align-items:center;justify-content:center;width:38px;height:38px;border-radius:10px;border:1px solid var(--color-border-primary);background:var(--color-bg-secondary);flex-shrink:0}.project-link-icon img{width:18px;height:18px;display:block}.project-title{font-size:1.3rem;font-weight:700;line-height:1.3;margin:0}.project-title-link{text-decoration-color:var(--color-secondary)!important;text-decoration-thickness:3px;text-underline-offset:4px}.project-tags{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0 12px}.project-tag{display:inline-flex;align-items:center;padding:4px 8px;border-radius:16px;font-size:.8rem;font-weight:400;line-height:1.8;background:var(--color-bg-light);color:var(--color-text-tertiary);border:1px solid var(--color-border-primary)}.project-desc{font-size:1rem;font-weight:600;line-height:1.8;color:var(--color-text-tertiary);margin:0 0 12px}.project-meta{display:flex;justify-content:flex-end;align-items:center;margin-top:auto}.project-date{font-size:.8rem;font-weight:300;line-height:1.8;color:var(--color-text-light)}
[data-theme="dark"] .project-card{background:#1c1c1e;border-color:#333;box-shadow:0 2px 6px rgba(255,255,255,.08)}[data-theme="dark"] .project-link-icon{background:#2c2c2e;border-color:#333}[data-theme="dark"] .project-tag{background:#58585c;border-color:#333;color:#aaa}[data-theme="dark"] .project-desc{color:#aaa}[data-theme="dark"] .project-date{color:#999}
@media (max-width:900px){.projects-grid{grid-template-columns:1fr;max-width:100%}}@media (max-width:768px){body{font-size:16px;line-height:1.6;-webkit-overflow-scrolling:touch}.site-container{padding:20px;max-width:100%}.about-section{padding:60px 0}.about-section h1{font-size:2.2em}.about-section p{font-size:1.1em}.about-section ul{padding-left:25px;font-size:1.1em}.app-header{padding-top:28px}}@media (max-width:640px){.project-card{padding:18px}.project-card-head{gap:12px}.project-title{font-size:1.15rem}}@media (max-width:480px){body{font-size:14px;line-height:1.5;-webkit-text-size-adjust:100%}.site-container{padding:15px}.about-section{padding:40px 0}.about-section h1{font-size:1.8em}.about-section p{font-size:1em;line-height:1.7}.about-section ul{padding-left:20px;font-size:1em}}@media (max-width:360px){body{font-size:13px;line-height:1.4}.site-container{padding:12px}.about-section{padding:30px 0}.about-section h1{font-size:1.6em}}
'''

Path('assets/styles/main.css').write_text(shared_css, encoding='utf-8')

style_link = '<link rel="stylesheet" href="assets/styles/main.css" />'
for file in files:
    path = Path(file)
    text = path.read_text(encoding='utf-8')
    text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.S)
    text = re.sub(r'<link rel="stylesheet" href="assets/styles/main.css"\s*/?>', '', text)
    if '</head>' in text:
        text = text.replace('</head>', style_link + '</head>', 1)
    text = text.replace('#9370DB', '#0a84ff').replace('rgb(147, 112, 219)', 'rgb(10, 132, 255)')
    path.write_text(text, encoding='utf-8')
    print(f'updated: {file}')
